### ISSUE TITLE
Error: "Cannot determine format of file:	/home/user/tmp/my_output/distmatrix.txt"

### ISSUE THREAD

**Issue by abedkurdi** [MBHallgren/MINTyper#6]
Hello there,

I am trying to use your package using nanopore samples, but I am getting the following error:
`Cannot determine format of file:	/home/user/my_output/distmatrix.txt`.

The `distmatrix` file is empty.

The command I am using is the following:
`mintyper --nanopore /home/user/samples/* --reference /home/user/GCA_008632635.1_ASM863263v1_genomic.fna --output /home/user/my_output --threads 50`.

Any idea what could be happening here?
Thank you in advance.

**Comment by abedkurdi** [comment]
Update:
the alignment is generating an empty `fsa` file. What could possibly be the reason: a problem in the reference genome? I am trying to run this pipeline using `nanopore` reads.

Thanks in advance for any suggestion!

**Comment by abedkurdi** [comment]
Update:
I found a problem in the reference FASTA, and the alignment worked.

Now, I am getting "No sufficient overlap was found" when running `ccphylo`. What do you suggest?

**Comment by MBHallgren** [comment]
Hi Abedkurdi,

What samples are you analyzing? MINTyper is developed for analyzing phylogeny between fairly related samples. If the diversity is too great (an example could be given input from different species), then there is not much relevant phylogeny to determine. This is usually where the 'No sufficient overlap was found' error is generated. CCphylo only includes positions of the input isolates which all can be aligned to the reference. An example:

Reference:       AAAAA
input_1 :           ABBBA
Input_2:           ACCCC
included_pos: A-----

So if the input samples are too diverse nearly all position will not be included by CCphylo.

I hope this helps.

**Comment by abedkurdi** [comment]
I am analyzing specific bacterial species. You are right, I found out that one of the samples (after assembly and blast) was of a different species. Once I excluded it from the analysis, I managed to get the newick file.

Thank you so much!

**Comment by MBHallgren** [comment]
Awesome!  I'll close this issue then.

Have a nice day! :)
